### ISSUE TITLE
Top page and succesfull login page freezing/loop

### ISSUE THREAD

**Issue by AkagiShiroe** [mauzel/mproxy-gbf#10] opened 2018-03-29 13:28 UTC
could you find what cause this?.. it seems the proxy just looping back sending zero package.
(chrome just keep spinning)

**Comment by mauzel** [comment] 2018-03-29 14:52
I sometimes encounter this but usually I just temporarily stop using the proxy to login, then re-enable the proxy after I finish logging in... because I was lazy to fix it and my primary goal is to play Granblue Fantasy so I never spent time investigating.

I will try to look into this but to be honest I don't know what actually triggers the login loop. Do you know how to reproduce the issue?

**Comment by AkagiShiroe** [comment] 2018-03-29 16:47
*urm.. maybe add some exception to some url? the server tries to send respond to chrome but gbf-proxy intercept it and chrome didn't fetch at all

**Comment by mauzel** [comment] 2018-03-29 16:50
That will probably work. This might be related to #5 but only occurs sometimes for some reason.

I'll try it out tonight.

**Comment by AkagiShiroe** [comment] 2018-03-29 17:05
yeah, that one too ,sometimes it just corrupt whole cookies

**Comment by mauzel** [comment] 2018-03-29 22:30
I cannot reproduce this issue, but I tried implementing a fix which is not a code fix, but a PAC file fix (completed in 4a94b26d13c66149a40331731360beb2f838f5e9).

I've added a new `gbf-proxy.pac` file to the root of this repository which you can use to ignore the authentication POST requests made by the game.

This issue unfortunately cannot be easily handled in the Python code, so I think this is a much quicker and less painful fix.

I will close this issue for now, but if this issue occurs again please open a new issue.

**Closed as completed by mauzel** 2018-03-29 22:30 UTC
Labels: bug
